namespace ContentStudio.Models;

/// <summary>
/// The editor description of one JSON field, generated by reflecting the Core definition type
/// and refined by <see cref="Services.SchemaOverrides"/>. The client renders a control per
/// <see cref="Kind"/>; anything it does not recognise falls back to a raw-JSON sub-editor,
/// so an unknown shape is always editable, never invisible.
/// </summary>
public sealed record FieldSchema
{
    /// <summary>The JSON key exactly as authored files write it.</summary>
    public required string Name { get; init; }

    public required string Label { get; init; }

    /// <summary>
    /// Control kind: <c>string · text · int · number · bool · enum · ref · refList · tags ·
    /// stringList · numberDict · object · objectList · objectDict · objectListDict ·
    /// moveGrantList · json</c>.
    /// </summary>
    public required string Kind { get; init; }

    /// <summary>Allowed values for <c>enum</c> fields (and datalist suggestions for strings).</summary>
    public IReadOnlyList<string>? EnumValues { get; init; }

    /// <summary>Name of a vocabulary list (from /api/vocabulary) that supplies the allowed
    /// values, for vocabularies that live in game data rather than a C# enum.</summary>
    public string? EnumSourceName { get; init; }

    /// <summary>Content type ids a <c>ref</c>/<c>refList</c> field may point at.</summary>
    public IReadOnlyList<string>? RefTypes { get; init; }

    /// <summary>For dict fields: which vocabulary supplies the keys
    /// (<c>properties · lanes · damageTypes · essences · attributes · traitCategories ·
    /// courseBonuses · modifierKeys · ownSlots</c>).</summary>
    public string? KeySource { get; init; }

    /// <summary>Item shape for <c>object*</c> kinds.</summary>
    public IReadOnlyList<FieldSchema>? Fields { get; init; }

    public double? Min { get; init; }
    public double? Max { get; init; }
    public double? Step { get; init; }
    public string? Help { get; init; }

    /// <summary>Nullable/optional fields render an "unset" state instead of a zero.</summary>
    public bool Optional { get; init; }
}
